spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petales
    username: petales
    password: petales
  mvc:
    servlet:
      load-on-startup: 1

mybatis:
  mapper-locations: classpath:resources/mapper/**/*.xml
  config-location: classpath:mapper/mapper-config.xml

